use_frameworks!

target 'Metron_Example' do
    pod 'Metron', :path => '../'
end

target 'Metron_Tests' do
    pod 'Metron', :path => '../'
    pod 'SwiftHamcrest', '~> 1.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end